version: "3.9"

services:
  turbo-repo:
    # image: utkusarioglu/react-native-android-devcontainer:1.0.17
    image: utkusarioglu/react-native-android-devcontainer:tag-unavailable
    environment:
      ANDROID_TARGET_DEVICE: android-host:58526
    extra_hosts:
      - android-host:host-gateway
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu/trials/turbo-repo
      - type: volume
        source: ccache
        target: /ccache
      - type: volume
        source: gradle
        target: /home/rn/.gradle
      - type: volume
        source: android
        target: /opt/android
    ports:
      - 3000:3000

volumes:
  ccache:
    name: turbo-repo-ccache
  gradle:
    name: turbo-repo-gradle
  android:
    name: turbo-repo-android
