name: "Build Android"
on:
  push:
    tags:
      - "**.**"
      - "experiment/**/**/**"
    paths:
      - src/**
      - .github/workflows/build-and-push.yml
  workflow_dispatch:
    
env:
  WORKING_DIR: /utkusarioglu/trials/turbo

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    container:
      image: utkusarioglu/react-native-android-devcontainer:tag-unavailable
      # image: utkusarioglu/react-native-android-devcontainer:1.0.17
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # repository: utkusarioglu/android
          path: ${{ env.WORKING_DIR }}

      - name: Install monorepo dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          yarn install --frozen-lockfile --production false

      - name: Build android
        working-directory: ${{ env.WORKING_DIR }}/apps/android
        run: |
          yarn build-release

      # - name: Upload to Google Drive
      #   uses: adityak74/google-drive-upload-git-action@main
      #   with:
      #     credentials: ${{ secrets.GOOGLE_DRIVE_TOKEN }}
      #     filename: android/android/app/build/outputs/apk/release/app-release.apk
      #     folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      #     overwrite: "true"

      - name: Builds as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: utkusarioglu-turbo-repo-android-release-build
          path: ${{ env.WORKING_DIR }}/apps/android/android/app/build/outputs/apk/release
