name: compile-android

on:
  # push:
  workflow_dispatch:

jobs:
  compile-android:
    name: compile-android
    runs-on: ubuntu-latest
    container:
      image: utkusarioglu/react-native-android-devcontainer:1.0.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: ops
        run: |
          echo "GCC"
          which gcc
          yarn
          ccache -s          
          yarn android
          ccache -s

      - name: Telegram notifications
        if: always()
        uses: utkusarioglu/telegram-notifications@main
        with:
          telegram_id: ${{ secrets.TELEGRAM_ID }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          job_status: ${{ job.status }}
          github_context: ${{ toJson(github) }}
